# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/
#
# Copyright © 2019 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

source 'https://rubygems.org'

gem 'absolute_time', '1.0.0'
gem 'builder', '3.2.4'
gem 'fastimage', '2.2.6'
gem 'java_properties'
gem 'journald-logger', '3.1.0'
gem 'jwt', '2.5.0'
gem 'locale', '2.1.3'
gem 'loofah', '2.19.1'
gem 'nokogiri', '~> 1.13.10', '>= 1.13.10'
gem 'open4', '1.3.4'
gem 'rb-inotify', '0.10.1'
gem 'redis', '4.8.1'
gem 'rubyzip', '2.3.2'
gem 'optimist'
gem 'resque', '2.5.0'
gem 'bbbevents', '2.0.0'
gem 'rake', '13.0.6'
gem 'tzinfo', '2.0.6'

group :test, optional: true do
  gem 'rubocop', '1.31.2'
  gem 'minitest', '5.14.4'
end
